version: 0.1.{build}
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-rc1'
configuration: Release
platform: Any CPU
build_script:
- cmd: psake ci
deploy:
- provider: NuGet
  api_key:
    secure: NNMetyZOFd94PObZltb2bG6VgWdh3g9tNJE80zwYfxP8L3Jq3v5zic9asFytPpgb
