version: 0.1.{build}
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-rc1'
configuration: Release
platform: Any CPU
build_script:
- cmd: psake ci
artifacts:
  path: 'build\**\MediaAccount.Client*.nupkg'
  name: Nuget
