version: 0.2.0.{build}
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
configuration: Release
platform: Any CPU
build_script:
- cmd: psake ci
artifacts:
-  path: 'build\**\MediaAccount.Client*-beta.nupkg'
   name: Nuget-Beta
-  path: 'build\**\MediaAccount.Client*.nupkg'
   name: Nuget
